#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1; do
  if [[ "${remote_ref##refs/heads/}" = "master" ]]; then
    echo "【WARM: .git/hooks/pre-push】"
    echo "masterに直接pushしようとしたため処理を中止しました。"
    echo "このリポジトリでmasterにpushしたい場合は .git/hooks/pre-push を削除してください。"
    exit 1
  fi
done
